### ISSUE TITLE
uninterned symbol in template

### ISSUE THREAD

**Issue by jsirex** [lockie/cookiecutter-lisp-game#2]
I'm new to cl, but in src/main.lisp#L1

`(in-package #:{{cookiecutter.project_slug}})`

 should be  without `#`

 `(in-package :{{cookiecutter.project_slug}})`

or not?

**Comment by lockie** [comment]
It'd work both ways, since the argument to [`in-package`](https://www.lispworks.com/documentation/HyperSpec/Body/m_in_pkg.htm) supposed to be a string designator, and both uninterned symbol and keyword are string designators.

**Comment by jsirex** [comment]
Ok, I see. I'm just thinking about consistency in styles and what is better. I saw other libraries  just use in-package :symbol

**Comment by lockie** [comment]
Some libraries (e.g. [cl-tiled](https://github.com/Zulu-Inuoe/cl-tiled/blob/master/src/tiled-json.lisp#L16)) use the uninterned symbol. I guess there's no best practice here 😅
